---
title: "Workspace-r"
author: "Twixer"
output: 
    html_document :
        toc: true
        theme: united
    md_document :
        fig_retina: true
---
    
``` {r global_options, echo=F}
library(knitr,quietly = T)
opts_chunk$set(echo= TRUE, 
               results='asis')
```

# Introduction
My R workspace with common scripts and templates. 

# Scripts
The scripts directory contains some usefull common scripts :

* startup.R : libraries to install in a new R install
* resetPar.R : reset to default the graphic options
* add_jre_to_java_home.R : append "jre"" at the **JAVA_HOME** env variable
* microbenchmark.R : a sample script to illustrate how to microbenchmark with R
* ram_profile.R : a sample script to illustrate how to monitor RAM/CPU usage

# Templates
A template directory for R scripts and other files :

* getting_cleaning_saving_data.R : a template R script in order to perform first basics operations on data (get, clean, save)

# References

## R

  R Core Team (2014). R: A language and environment
  for statistical computing. R Foundation for
  Statistical Computing, Vienna, Austria. URL
  http://www.R-project.org/.